<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSahHcYp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSahHcYp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSahHcYp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSahHcYp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSahHcYp\App_KernelDevDebugContainer([
    'container.build_hash' => 'SahHcYp',
    'container.build_id' => '7b87732b',
    'container.build_time' => 1666883533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSahHcYp');
